---
- hosts: node02
  vars: 
   - remote_dir: /etc/ansible/facts.d
   - facts_file: custom.fact

  tasks:
    - name: "create a directory"
      file:
        path: "{{ remote_dir }}"
        recurse: yes
        state: directory

    - name: "copy the content"
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"


