---
- name: "Configure apache"
  hosts: node01

  tasks:
    - name: "update the server"
      apt: 
        update_cache: yes

    - name: "install apache2"
      apt:
        name: apache2
        state: absent 

    - name: "start the service"
      service:
        name: apache2
        state: started
