---
- name: "testing handler"
  hosts: node02

  tasks:
  - name: install nginx
    apt:
      name: nginx
      state: present
    notify: restart nginx

  - name: copy file
    copy:
      src: index.html
      dest: /usr/share/nginx/html
    notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
