apiVersion: v1
kind: LimitRange
metadata:
  name: limit1
  namespace: ashwin
spec:
  limits:
  - default:
      memory: 512M
      cpu: 100m
    defaultRequest:
      memory: 256M
      cpu: 50m
    max:
      memory: 1G
      cpu: 1
    min:
      memory: 100M
      cpu: 50m
    type: Container

