apiVersion: v1
kind: Pod
metadata:
  name: multiapp
spec:
  containers: 
  - name: vm1
    image: nginx
    ports:
      - containerPort: 80

  - name: vm2
    image: redis

  - name: vm3
    image: nginx


