apiVersion: v1
kind: Pod
metadata:
  name: appapr35
  namespace: ashwin
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        memory: 150M
        cpu: 100m
      limits:
        memory: 2G
        cpu: 200m


